<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EmailTemplates\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scriban" Version="7.2.4" />
  </ItemGroup>

</Project>
