namespace Bloodsport.Core.Teams;

/// <summary>
/// A statistical profile built from a player's op.gg data and Riot match history.
/// This is the input to the team formation algorithm.
/// Every field is derived from real game data — not self-reported.
/// </summary>
public class PlayerProfile
{
    public Guid PlayerId { get; set; }
    public string SummonerName { get; set; } = string.Empty;
    public string Region { get; set; } = "NA1";

    // ── Role Data ────────────────────────────────────────────────────────
    // Proficiency per role: 0.0 (never plays) to 1.0 (main)
    // Derived from games played + win rate per role over last 100 games
    public Dictionary<string, double> RoleProficiency { get; set; } = new()
    {
        ["TOP"] = 0, ["JUNGLE"] = 0, ["MID"] = 0, ["ADC"] = 0, ["SUPPORT"] = 0
    };
    public string PrimaryRole => RoleProficiency.OrderByDescending(r => r.Value).First().Key;
    public string SecondaryRole => RoleProficiency.OrderByDescending(r => r.Value).Skip(1).First().Key;

    // ── Playstyle Vector ─────────────────────────────────────────────────
    // Derived from champion pool and stat patterns over recent games.
    // Each dimension is 0.0 to 1.0.
    public double AggressionIndex { get; set; }      // high KDA fights, early skirmishes
    public double UtilityIndex { get; set; }          // assists, vision, peel behavior
    public double CarryCapacity { get; set; }         // damage share, scaling champions
    public double ObjectiveFocus { get; set; }        // dragon/baron participation rate
    public double ConsistencyRating { get; set; }     // low variance performance

    // ── Champion Pool Tags ───────────────────────────────────────────────
    // What strategic identities does this player bring?
    // A player with Engage:0.8 brings initiation. Peel:0.9 protects carries.
    public double EngagePotential { get; set; }       // initiators (Malphite, Amumu, etc.)
    public double PeelPotential { get; set; }         // protectors (Lulu, Janna, etc.)
    public double PokePotential { get; set; }         // poke/zone champions
    public double SplitPushPotential { get; set; }    // 1v1/split pressure
    public double TeamfightPotential { get; set; }    // AoE teamfight champions

    // ── Statistical Profile (from op.gg / Riot API) ──────────────────────
    public double AverageKDA { get; set; }
    public double AverageCSPerMin { get; set; }
    public double AverageVisionScore { get; set; }
    public double AverageDamageShare { get; set; }    // % of team damage
    public double WinRateLast30 { get; set; }
    public double AverageGameImpact { get; set; }     // op.gg GI score normalized 0-1
    public int RankedGamesAnalyzed { get; set; }

    // ── BSR / TrueSkill ──────────────────────────────────────────────────
    public double BSR { get; set; }
    public double TrueSkillMu { get; set; }
    public double TrueSkillSigma { get; set; }

    // ── Data Source ──────────────────────────────────────────────────────
    public DateTime ProfileBuiltAt { get; set; }
    public string DataSource { get; set; } = "mock"; // "riot_api" | "opgg" | "mock"
}

/// <summary>
/// A team of 5 players with a computed chemistry score.
/// Teams are formed by the TeamFormationService — never hand-picked.
/// </summary>
public class FormedTeam
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string TeamName { get; set; } = string.Empty; // generated by the system
    public List<TeamSlot> Slots { get; set; } = new();

    // ── Team Chemistry Score (TCS) ───────────────────────────────────────
    // The primary quality metric. Higher = better internal synergy.
    public double TeamChemistryScore { get; set; }

    // Sub-scores — all visible on the team reveal page
    public double RoleCoverageScore { get; set; }        // do all 5 roles complement each other?
    public double PlaystyleBalanceScore { get; set; }    // aggression balanced with utility?
    public double ChampionPoolDepthScore { get; set; }   // how many viable team comps can they run?
    public double WinConditionDiversityScore { get; set; } // can they win multiple ways?
    public double SkillVarianceScore { get; set; }        // skill spread within the team (lower = more even)

    // Average BSR of the team — used for inter-team balance
    public double AverageBSR => Slots.Average(s => s.Player.BSR);

    public bool IsComplete => Slots.Count == 5 &&
        Slots.Select(s => s.AssignedRole).Distinct().Count() == 5;
}

public class TeamSlot
{
    public PlayerProfile Player { get; set; } = null!;
    public string AssignedRole { get; set; } = string.Empty;
    public double RoleFitScore { get; set; } // how well this player fits the assigned role
}
