// <auto-generated />
using System;
using Bloodsport.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bloodsport.Data.Sql.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20260705012621_TeamInviteType")]
    partial class TeamInviteType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bloodsport.Entity.Database.Playoff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RiotProviderId")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RiotTournamentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("Playoffs");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRound", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PlayoffId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayoffId");

                    b.ToTable("PlayoffRounds");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRoundMatchup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NextMatchupId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayoffRoundId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamOneId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamTwoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TournamentCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NextMatchupId");

                    b.HasIndex("PlayoffRoundId");

                    b.HasIndex("TeamOneId");

                    b.HasIndex("TeamTwoId");

                    b.ToTable("PlayoffRoundMatchups");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRoundMatchupResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("PlayoffRoundMatchupId")
                        .HasColumnType("bigint");

                    b.Property<long>("WinningTeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayoffRoundMatchupId");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("PlayoffRoundMatchupResults");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("PlayoffId")
                        .HasColumnType("bigint");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayoffId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayoffTeams");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PostComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.RiotAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RiotAccounts");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.RiotAccountRecruitment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsLookingForTeam")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Lanes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RiotAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RiotAccountId")
                        .IsUnique();

                    b.ToTable("RiotAccountRecruitments");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.RiotLobbyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TournamentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RiotLobbyEvents");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("EstimatedDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimatedDateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RegistrationOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("RiotProviderId")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RiotTournamentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonMatchupParameters", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MapType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<string>("SpectatorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("SeasonMatchupParameters");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("InauguralRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("SeasonRegistrations");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeek", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasBeenEnded")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonWeeks");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeekMatchup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeasonWeekId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamOneId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamTwoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TournamentCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonWeekId");

                    b.HasIndex("TeamOneId");

                    b.HasIndex("TeamTwoId");

                    b.ToTable("SeasonWeekMatchups");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeekMatchupResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("DidNotPlay")
                        .HasColumnType("bit");

                    b.Property<bool>("RosterMismatch")
                        .HasColumnType("bit");

                    b.Property<long>("SeasonWeekMatchupId")
                        .HasColumnType("bigint");

                    b.Property<long>("WinnerTeamAverageGPM")
                        .HasColumnType("bigint");

                    b.Property<long?>("WinnerTeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SeasonWeekMatchupId")
                        .IsUnique();

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("SeasonWeekMatchupResults");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("RiotAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RiotAccountId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamInvites");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("RiotAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RiotAccountId");

                    b.HasIndex("TeamId", "RiotAccountId")
                        .IsUnique();

                    b.ToTable("TeamMemberships");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamPlayoffRoster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("PlayoffId")
                        .HasColumnType("bigint");

                    b.Property<string>("RosterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayoffId");

                    b.HasIndex("TeamId", "PlayoffId")
                        .IsUnique();

                    b.ToTable("TeamPlayoffRosters");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamRecruitment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsLookingForUser")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Lanes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamRecruitments");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamSeasonResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("LoseCount")
                        .HasColumnType("int");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.Property<double>("WinnerTeamAverageGPM")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique();

                    b.ToTable("TeamSeasonResults");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamSeasonRoster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RosterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique();

                    b.ToTable("TeamSeasonRosters");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Playoff", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Season", "Season")
                        .WithOne("Playoff")
                        .HasForeignKey("Bloodsport.Entity.Database.Playoff", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRound", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Playoff", "Playoff")
                        .WithMany("PlayoffRounds")
                        .HasForeignKey("PlayoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playoff");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRoundMatchup", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.PlayoffRoundMatchup", "NextMatchup")
                        .WithMany()
                        .HasForeignKey("NextMatchupId");

                    b.HasOne("Bloodsport.Entity.Database.PlayoffRound", "PlayoffRound")
                        .WithMany("PlayoffMatchups")
                        .HasForeignKey("PlayoffRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.PlayoffTeam", "TeamOne")
                        .WithMany()
                        .HasForeignKey("TeamOneId");

                    b.HasOne("Bloodsport.Entity.Database.PlayoffTeam", "TeamTwo")
                        .WithMany()
                        .HasForeignKey("TeamTwoId");

                    b.Navigation("NextMatchup");

                    b.Navigation("PlayoffRound");

                    b.Navigation("TeamOne");

                    b.Navigation("TeamTwo");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRoundMatchupResult", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.PlayoffRoundMatchup", "PlayoffRoundMatchup")
                        .WithMany("PlayoffRoundMatchupResults")
                        .HasForeignKey("PlayoffRoundMatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.PlayoffTeam", "WinningTeam")
                        .WithMany("PlayoffRoundMatchupResults")
                        .HasForeignKey("WinningTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayoffRoundMatchup");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffTeam", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Playoff", "Playoff")
                        .WithMany("PlayoffTeams")
                        .HasForeignKey("PlayoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("PlayoffTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playoff");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Post", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PostComment", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.User", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.RiotAccount", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.User", "User")
                        .WithMany("RiotAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.RiotAccountRecruitment", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.RiotAccount", "RiotAccount")
                        .WithOne("RiotAccountRecruitment")
                        .HasForeignKey("Bloodsport.Entity.Database.RiotAccountRecruitment", "RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonMatchupParameters", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Season", "Season")
                        .WithOne("MatchupParameters")
                        .HasForeignKey("Bloodsport.Entity.Database.SeasonMatchupParameters", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonRegistration", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Season", "Season")
                        .WithMany("SeasonRegistrations")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("SeasonRegistrations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeek", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Season", "Season")
                        .WithMany("SeasonWeeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeekMatchup", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.SeasonWeek", "SeasonWeek")
                        .WithMany("SeasonWeekMatchups")
                        .HasForeignKey("SeasonWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "TeamOne")
                        .WithMany()
                        .HasForeignKey("TeamOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "TeamTwo")
                        .WithMany()
                        .HasForeignKey("TeamTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeasonWeek");

                    b.Navigation("TeamOne");

                    b.Navigation("TeamTwo");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeekMatchupResult", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.SeasonWeekMatchup", "SeasonWeekMatchup")
                        .WithOne("SeasonWeekMatchupResult")
                        .HasForeignKey("Bloodsport.Entity.Database.SeasonWeekMatchupResult", "SeasonWeekMatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "WinnerTeam")
                        .WithMany("SeasonWeekMatchupResults")
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SeasonWeekMatchup");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Team", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.User", "Manager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamInvite", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.RiotAccount", "RiotAccount")
                        .WithMany("TeamInvites")
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("TeamInvites")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamMembership", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.RiotAccount", "RiotAccount")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamPlayoffRoster", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Playoff", "Playoff")
                        .WithMany("TeamPlayoffRosters")
                        .HasForeignKey("PlayoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("TeamPlayoffRosters")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playoff");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamRecruitment", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithOne("TeamRecruitment")
                        .HasForeignKey("Bloodsport.Entity.Database.TeamRecruitment", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamSeasonResult", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Season", "Season")
                        .WithMany("TeamSeasonResults")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("TeamSeasonResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.TeamSeasonRoster", b =>
                {
                    b.HasOne("Bloodsport.Entity.Database.Season", "Season")
                        .WithMany("TeamSeasonRosters")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloodsport.Entity.Database.Team", "Team")
                        .WithMany("TeamSeasonRosters")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Playoff", b =>
                {
                    b.Navigation("PlayoffRounds");

                    b.Navigation("PlayoffTeams");

                    b.Navigation("TeamPlayoffRosters");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRound", b =>
                {
                    b.Navigation("PlayoffMatchups");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffRoundMatchup", b =>
                {
                    b.Navigation("PlayoffRoundMatchupResults");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.PlayoffTeam", b =>
                {
                    b.Navigation("PlayoffRoundMatchupResults");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Post", b =>
                {
                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.RiotAccount", b =>
                {
                    b.Navigation("RiotAccountRecruitment")
                        .IsRequired();

                    b.Navigation("TeamInvites");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Season", b =>
                {
                    b.Navigation("MatchupParameters")
                        .IsRequired();

                    b.Navigation("Playoff")
                        .IsRequired();

                    b.Navigation("SeasonRegistrations");

                    b.Navigation("SeasonWeeks");

                    b.Navigation("TeamSeasonResults");

                    b.Navigation("TeamSeasonRosters");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeek", b =>
                {
                    b.Navigation("SeasonWeekMatchups");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.SeasonWeekMatchup", b =>
                {
                    b.Navigation("SeasonWeekMatchupResult");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.Team", b =>
                {
                    b.Navigation("PlayoffTeams");

                    b.Navigation("SeasonRegistrations");

                    b.Navigation("SeasonWeekMatchupResults");

                    b.Navigation("TeamInvites");

                    b.Navigation("TeamMemberships");

                    b.Navigation("TeamPlayoffRosters");

                    b.Navigation("TeamRecruitment")
                        .IsRequired();

                    b.Navigation("TeamSeasonResults");

                    b.Navigation("TeamSeasonRosters");
                });

            modelBuilder.Entity("Bloodsport.Entity.Database.User", b =>
                {
                    b.Navigation("ManagedTeams");

                    b.Navigation("PostComments");

                    b.Navigation("Posts");

                    b.Navigation("RiotAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
