<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d5f16902-fa25-4ba5-8159-f2e9a2f9fc29</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Bloodsport.Data.Sql\Bloodsport.Data.Sql.csproj" />
    <ProjectReference Include="..\..\Libraries\Bloodsport.Entity\Bloodsport.Entity.csproj" />
  </ItemGroup>

</Project>
