<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>50e22b70-7efe-429d-98e5-dcdbea33d201</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="EmailTemplates\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0" />
    <PackageReference Include="Camille.RiotGames" Version="3.0.0-nightly-2025-06-24-d2b94715b7" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.10.0" />
    <PackageReference Include="Scriban" Version="7.2.4" />
    <ProjectReference Include="..\..\..\Libraries\Bloodsport.Data.Sql\Bloodsport.Data.Sql.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Bloodsport.Entity\Bloodsport.Entity.csproj" />
    <ProjectReference Include="..\BloodsportSite.Client\BloodsportSite.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
